---
title: "makeplot"
author: "Claus Ekstrøm"
date: "15 Jun 2015"
output: html_document
---

```{r, echo=TRUE}
indata <- read.csv2("data.csv", header=TRUE, dec=".")
tid <- ifelse(indata$date<600, 531 - indata$date+18, 618 - indata$date)
tid <- tid + (24-floor(indata$time/100)*60 + (60 - indata$time %% 100 ))/1440
tid <- -tid
#llr$b <- llr$tid + (24-llr[,2])
                                # save time
#                                b=row[1]
#                                h=d+(float((24-float(b[:2]))*60+60-float(b[2:4])))/1440
#                                time.append(h)



llr <- as.data.frame(lapply(1:4, function(i) { 1 / indata[,1+2*i] / (1/indata[,2+2*i] + 1/indata[,1+2*i])} ))


colnames(llr) <- c("Betfair", "DanskeSpil", "Unibet", "Nordicbet")

meandata <- data.frame(values=apply(llr, 1, mean), time=tid)
lowerdata <- round(100*(meandata$values-2*apply(llr, 1, sd)), 2)
upperdata <- round(100*(meandata$values+2*apply(llr, 1, sd)), 2)

llr$Gennemsnit <- meandata$values

llr <- stack(llr)
llr$values <- round(llr$values*100, 2)
llr$Firma <- llr$ind
llr$time <- rep(round(tid, 2), 5)

```

```{r}
library(knitr)
library(rCharts)
```


Her starter det sidste 

```{r, echo=FALSE,results='asis',comment=NA}

h1 = hPlot(x = "time", y = "values", groups = c("Firma"), data = llr,
           type = c("scatter", "scatter", "line", "scatter", "scatter"), 
           radius=4,
           zIndex=1)

areadata <- data.frame(x=round(meandata$time, 2), y=lowerdata, z=upperdata)

# Color needs to be hexcoded for opacity to work
h1$series(
  data = toJSONArray2(areadata[,1:3], names = F, json = F),
  name = "Simple pointwise 95% PI",
  type = 'arearange',
  fillOpacity = 0.3,
  lineWidth = 0,
  color = '#74BBFB',
  zIndex = -1
)

# Set output size and allow for zoom
h1$chart(zoomType = "xy",
         margin = list(left=100,right=100,top=100,bottom=200),
         width = 800, height = 600)

# h1$plotOptions(scatter = list(marker = list(symbol = 'circle')))
# h1$tooltip(formatter = "#! function() { return this.group + ', ' + this.y; } !#")

h1$xAxis(title = list(text = "Tid før valget (dage)"))
h1$yAxis(title = list(text = "Sandsynlighed for LLR, %"))

h1$exporting(enabled = TRUE)
# h1$plotOptions(column = list(dataLabels = list(enabled = T, rotation = -90, align = 'right', color = 'white', x = 4, y = 10)))
# h1$xAxis(type = "category", labels = list(rotation = 90, align = "left"))
# h1$legend(margin = 30)

h1$print('iframesrc', cdn =TRUE, include_assets=TRUE)

h1$save('fv15.html', standalone=TRUE)


```

